### ISSUE TITLE
Is it higher quality audio to use this with audio/wav than the standard audio encoding for media recorder?

### ISSUE THREAD

**Issue by trackedsupport** [CameraKit/webm-media-recorder#34]
Right now I'm using mp4 or webm with the default audio encoding options but was wondering if the audio being saved is compressed. So if I use audio/wav with something like this, will it then not be compressed and be higher quality? Thanks!

**Comment by exPHAT** [comment]
This library doesn't support wav like it's original parent repo does, so I'm going to close this issue.

As for your question, I wouldn't count on the wav recording being a higher quality even though it's technically "uncompressed". These projects are intended as a polyfill to add support to browsers which otherwise don't have the ability to record webm/wav, not as a lossless audio storage library.

**Comment by trackedsupport** [comment]
Thanks for the update!
